# Generated by Django 4.0.4 on 2022-08-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(blank=True, choices=[('ADMIN', 'admin'), ('MANAGER', 'manager'), ('AGENT', 'agent')], max_length=10, null=True),
        ),
    ]
